#pragma once

#define COMBO_TERM 50
#define COMBO_COUNT 38
#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD
// #define USB_MAX_POWER_CONSUMPTION 50
// #define TAPPING_TERM 350

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_WHEEL_DELAY 0
